name: "Generate Versioning"
description: "Generate the package version based on the PR title"
inputs:
  application_repo:
    description: "application repo (unused here but kept for compatibility)"
    required: false
  version_deploy_token: 
    description: "token to push to the repo"
    required: true
    default: 'secrets.VERSION_DEPLOY_TOKEN'
runs:
  using: "composite"
  steps:
    - name: Compute new version and write package.json
      id: compute
      shell: bash
      run: |
        set -euo pipefail
        # Get the commit message from the pull request title
        COMMIT_MESSAGE=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        echo "Commit Message: $COMMIT_MESSAGE"

        # Extract the current image version from package.json
        IMAGE_VERSION=$(jq -r .version package.json)
        echo "Current version: $IMAGE_VERSION"

        # Parse major, minor, and patch version numbers
        IFS='.' read -r major minor patch <<< "$IMAGE_VERSION"

        # Enable case-insensitive matching for commit message
        shopt -s nocasematch

        # Determine the new package version based on the commit message
        if [[ $COMMIT_MESSAGE == feature* ]]; then
          packageJsonVersion="${major}.$((minor + 1)).$patch"
        elif [[ $COMMIT_MESSAGE == bugfix* || $COMMIT_MESSAGE == hotfix* ]]; then
          packageJsonVersion="${major}.$minor.$((patch + 1))"
        else
          echo "Can not determine commit prefix - COMMIT_MESSAGE: $COMMIT_MESSAGE"
          exit 1
        fi

        # Disable case-insensitive matching if needed
        shopt -u nocasematch

        if [ "$packageJsonVersion" != "" ]; then
          echo "New package.json version: $packageJsonVersion"
          jq --arg new_version "$packageJsonVersion" '.version = $new_version' package.json > tmpfile && mv tmpfile package.json
        fi
        
        echo "new_version=v${packageJsonVersion}" >> "$GITHUB_OUTPUT"

    - name: Commit changes to package.json
      shell: bash
      run: |
        set -euo pipefail
        git config user.email "devops@matechstudios.com"
        git config user.name  "matechbot"
        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: bump version to v${{ steps.compute.outputs.new_version#v }}"
        fi

        # This uses the token from actions/checkout (persist-credentials: true)
        # Requires bypass on your ruleset/branch protection to succeed
        git push https://matechbot:$VERSION_DEPLOY_TOKEN@github.com/Matech-Studios/$APPLICATION_REPO.git HEAD:main
outputs:
  new_version:
    value: ${{ steps.compute.outputs.new_version }}