name: DWP UI Backoffice - Continuous Deployment
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
        contents: write
        packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.VERSION_DEPLOY_TOKEN }}

      - name: Modify version
        uses: ./.github/actions/generate-versioning
        with:
          version_deploy_token: ${{ secrets.VERSION_DEPLOY_TOKEN }}
          application_repo: fe-react-lib
    
      - name: Set up package version
        id: image_version
        run: |
            echo "IMAGE_VERSION=v$(jq -r .version package.json)" >> $GITHUB_ENV
  
    outputs:
        package_version: ${{ env.IMAGE_VERSION }}

  publish_to_npm:
    name: Publish package to NPM
    runs-on: ubuntu-latest
    
    permissions:
        contents: read
        packages: write
    
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - name: Publish
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
      
      - name: Update package version
        run: npm version ${PACKAGE_VERSION} --no-git-tag-version
        env:
          PACKAGE_VERSION: ${{ needs.build.outputs.package_version }}
    
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
