# name: DWP UI Backoffice - Continuous Deployment
# on:
#   pull_request:
#     branches:
#       - main
#     types:
#       - closed

# jobs:
#   build:
#     name: Build & Push Docker Image
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           token: ${{ secrets.VERSION_DEPLOY_TOKEN }}

#       - name: Modify version
#         uses: ./.github/actions/generate-versioning
#         with:
#           version_deploy_token: ${{ secrets.VERSION_DEPLOY_TOKEN }}
#           application_repo: fe-react-lib

#       - name: Set up Image tag
#         id: image_version
#         run: |
#           echo "IMAGE_VERSION=v$(jq -r .version package.json)" >> $GITHUB_ENV

#     outputs:
#       image_version: ${{ env.IMAGE_VERSION }}

#   deploy_to_npm:
#     name: Deploy to NPM
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Deploy
#         uses: ./.github/actions/deploy-argo
#         with:
#           image_version: ${{needs.build.outputs.image_version}}
#           pipeline_deploy_token: ${{ secrets.PIPELINE_DEPLOY_TOKEN }}
#           environment: development
#           application_name: dwp-ui-backoffice
#           application_repo: matech-dwp-k8s
